# Generated by Django 3.2.3 on 2021-12-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compeapp', '0002_hackathon'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=150, unique=True)),
                ('c_date', models.DateField()),
                ('last_date', models.DateField()),
                ('c_type', models.CharField(max_length=150)),
                ('num_round', models.IntegerField()),
                ('venue', models.CharField(max_length=150)),
                ('c_link', models.CharField(max_length=150)),
            ],
        ),
    ]
