# Generated by Django 3.2.3 on 2021-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compeapp', '0003_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=150, unique=True)),
                ('e_date', models.DateField()),
                ('last_date', models.DateField()),
                ('venue', models.CharField(max_length=150)),
                ('e_link', models.CharField(max_length=150)),
                ('e_speaker', models.CharField(max_length=150, unique=True)),
                ('timing', models.IntegerField()),
            ],
        ),
    ]
