# Generated by Django 3.2.3 on 2021-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=150, unique=True)),
                ('h_date', models.DateField()),
                ('last_date', models.DateField()),
                ('venue', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
